In [6]:
import jax
import jax.numpy as jnp
import numpy as np

x = np.random.uniform(size=(8, 5))
x

array([[0.74846189, 0.66809494, 0.47797335, 0.12540713, 0.53845091],
       [0.31844752, 0.87175618, 0.33980863, 0.62387088, 0.51414225],
       [0.27843608, 0.46097453, 0.68763947, 0.20671724, 0.0991383 ],
       [0.83001061, 0.26529253, 0.07931531, 0.33477647, 0.88012424],
       [0.19659086, 0.16888628, 0.21077355, 0.70533663, 0.87952009],
       [0.53674102, 0.39840743, 0.16033322, 0.49332368, 0.8353387 ],
       [0.40141289, 0.94911805, 0.47351867, 0.70067011, 0.24443842],
       [0.14676606, 0.51256606, 0.48544686, 0.33109136, 0.71694867]])

In [11]:
np.concatenate([np.expand_dims(x, axis=-1)] * 3, axis=-1)

array([[[0.74846189, 0.74846189, 0.74846189],
        [0.66809494, 0.66809494, 0.66809494],
        [0.47797335, 0.47797335, 0.47797335],
        [0.12540713, 0.12540713, 0.12540713],
        [0.53845091, 0.53845091, 0.53845091]],

       [[0.31844752, 0.31844752, 0.31844752],
        [0.87175618, 0.87175618, 0.87175618],
        [0.33980863, 0.33980863, 0.33980863],
        [0.62387088, 0.62387088, 0.62387088],
        [0.51414225, 0.51414225, 0.51414225]],

       [[0.27843608, 0.27843608, 0.27843608],
        [0.46097453, 0.46097453, 0.46097453],
        [0.68763947, 0.68763947, 0.68763947],
        [0.20671724, 0.20671724, 0.20671724],
        [0.0991383 , 0.0991383 , 0.0991383 ]],

       [[0.83001061, 0.83001061, 0.83001061],
        [0.26529253, 0.26529253, 0.26529253],
        [0.07931531, 0.07931531, 0.07931531],
        [0.33477647, 0.33477647, 0.33477647],
        [0.88012424, 0.88012424, 0.88012424]],

       [[0.19659086, 0.19659086, 0.19659086],
        [0.16888628, 0.168

In [4]:
x = x[..., jnp.newaxis]
x = jnp.repeat(x, 3, axis=2)
x

Array([[[0.4882965 , 0.4882965 , 0.4882965 ],
        [0.5454168 , 0.5454168 , 0.5454168 ],
        [0.42934033, 0.42934033, 0.42934033],
        [0.8201506 , 0.8201506 , 0.8201506 ],
        [0.26274708, 0.26274708, 0.26274708]],

       [[0.7616482 , 0.7616482 , 0.7616482 ],
        [0.80786496, 0.80786496, 0.80786496],
        [0.3995452 , 0.3995452 , 0.3995452 ],
        [0.77759725, 0.77759725, 0.77759725],
        [0.06890023, 0.06890023, 0.06890023]],

       [[0.8492769 , 0.8492769 , 0.8492769 ],
        [0.3977302 , 0.3977302 , 0.3977302 ],
        [0.6356223 , 0.6356223 , 0.6356223 ],
        [0.06240422, 0.06240422, 0.06240422],
        [0.3563945 , 0.3563945 , 0.3563945 ]],

       [[0.6470544 , 0.6470544 , 0.6470544 ],
        [0.65041393, 0.65041393, 0.65041393],
        [0.7988266 , 0.7988266 , 0.7988266 ],
        [0.07475065, 0.07475065, 0.07475065],
        [0.48319602, 0.48319602, 0.48319602]],

       [[0.41804302, 0.41804302, 0.41804302],
        [0.2876466 , 0.287